FROM ubuntu:20.04 AS builder

RUN apt-get update && \
    apt-get install -y make mpich gfortran gawk && \
    rm -rf /var/lib/apt/lists/*

COPY ./parafem /parafem
WORKDIR /parafem
RUN ./make-parafem MACHINE=linuxdesktop

FROM ubuntu:20.04
RUN apt-get update && \
    apt-get install -y gawk && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /parafem/src/tools/postprocessing/pf2ensi/pf2ensi /usr/local/bin/
COPY --from=builder /parafem/src/tools/postprocessing/pf2ensi/pf2ensi.geo.awk /usr/local/bin/
COPY --from=builder /parafem/src/tools/postprocessing/pf2ensi/pf2ensi.var.awk /usr/local/bin/

WORKDIR /work
