FROM ubuntu:20.04 AS builder

RUN apt-get update && \
    apt-get install -y make mpich gfortran gawk && \
    rm -rf /var/lib/apt/lists/*

COPY ./parafem /parafem
WORKDIR /parafem
RUN ./make-parafem MACHINE=linuxdesktop

FROM ubuntu:20.04
RUN apt-get update && \
    apt-get install -y mpich && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /parafem/bin/p123 /usr/local/bin/

WORKDIR /work
